# Generated by Django 2.0.5 on 2018-05-24 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('O1', '3A Ecole'), ('O2', '3A M2 imbriques stage M2 et PFE'), ('O3', '3A M2 imbriques 3 cours supplementaires'), ('O4', '3A M2 imbriques 2 cours 1 projet')], max_length=2)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours.Master')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='master',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
