# Generated by Django 2.0.5 on 2018-05-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0006_auto_20180525_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours.Option'),
        ),
    ]
