# Generated by Django 2.0.5 on 2018-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0008_courses_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='troisa_possible',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(to='parcours.Courses'),
        ),
    ]
