# Generated by Django 2.0.5 on 2018-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0009_auto_20180526_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='troisa_possible',
            field=models.BooleanField(default=1),
        ),
    ]
