# Generated by Django 2.0.5 on 2018-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0010_auto_20180526_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='nb_cours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='nb_ects_cours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='nb_ects_projet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='nb_projet',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
