# Generated by Django 2.0.5 on 2018-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0011_auto_20180526_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='obligatoire',
            field=models.BooleanField(default=0),
        ),
    ]
