# Generated by Django 2.0.5 on 2018-05-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0012_courses_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='parcours.Master'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='parcours.Option'),
        ),
    ]
