# Generated by Django 2.0.5 on 2018-05-26 15:39

from django.db import migrations, models
import django.db.models.deletion
import parcours.models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0013_auto_20180526_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='master',
            field=models.ForeignKey(default=parcours.models.UserProfile.default_master, on_delete=django.db.models.deletion.SET_DEFAULT, to='parcours.Master'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.ForeignKey(default=parcours.models.UserProfile.default_option, on_delete=django.db.models.deletion.SET_DEFAULT, to='parcours.Option'),
        ),
    ]
